### ISSUE TITLE
Add contributors list

### ISSUE THREAD

**Issue by MathieuSoysal** [MathieuSoysal/Javadoc-publisher.yml#37]
## Problem

The *Javadoc-publisher.yml* project doesn't have a contributors list at the end of the *README.md*.

## Solution

To resolve it we can use this GitHub Actions : [contributors-list](https://github.com/marketplace/actions/contributors-list).

**Comment by n-tdi** [comment]
Is this being worked on or done? If not then I can make it.

**Comment by n-tdi** [comment]
Will PR shortly
