### ISSUE TITLE
Doc: Inputs list

### ISSUE THREAD

**Issue by MathieuSoysal** [MathieuSoysal/Javadoc-publisher.yml#43]
## Problem

Currently, we cannot see directly all possible inputs with  [Javadoc-publisher.yml](https://github.com/MathieuSoysal/Javadoc-publisher.yml), and we need to check them manually inside the *action.yml* file to see inputs.

## Solution

To resolve it we can add a section like that:

<details>

<summary>

### Inputs

</summary>

| input        | description                   | default |
|--------------|-------------------------------|--------:|
| java-version | the java version your project | 11      |

</details>

To easily create a Markdown table : [stevecat/table-magic](https://github.com/stevecat/table-magic).

**Comment by priyankdixit** [comment]
@MathieuSoysal Hello,I can solve the issue.....can you assign me please?

**Comment by priyankdixit** [comment]
Actually I m new to open source ,I know reading YAML files and have gone through code in action.yml.
Can u specify a little as how can I creak Markdown table and where we have to input it?(only hints required)
Your time and efforts for a newbie would be definately appreciated

**Comment by priyankdixit** [comment]
As far as I have understood ,I have nothing to do with the code,but I have to create a section for the repository specifying inputs in a table?

**Comment by priyankdixit** [comment]
@MathieuSoysal  Please verify my work!
