### ISSUE TITLE
Build Folder Does Not Exist

### ISSUE THREAD

**Issue by poyrazinan** [MathieuSoysal/Javadoc-publisher.yml#87]
Hello,

How can i fix this issue?

> Error: The directory you're trying to deploy named /home/runner/work/JavaLicense/JavaLicense/target/site/apidocs doesn't exist. Please double check the path and any prerequisite build scripts and try again.

I've seen #73 this issue but couldn't understand the fix.

Is there any idea for fix this? Should i create the folder?

Thank you 👐 

My Project Workflow: https://github.com/poyrazinan/JavaLicense/blob/main/.github/workflows/publish-javadoc-maven.yml

**Comment by brenoepics** [comment]
Hi, I took a look at your project's CI.

![image](https://github.com/user-attachments/assets/10b04034-0192-4ed4-8a13-eb1544072dac)

shouldn't it be `target/reports/apidocs`?

**Comment by isaacmaffeis** [comment]
Hello,

I encountered the same issue and was able to resolve it by adding the following option to the .yml file after `target-folder`:
```yaml
javadoc-source-folder: target/report/apidocs
```
This change points to the correct folder where the Javadoc is generated. Once I updated this in the workflow, the deployment worked as expected.

I hope this helps!

**Comment by lewmilburn** [comment]
That didn't work for me :( any idea how to fix? Thanks! https://github.com/LewMC/Essence/blob/main/.github/workflows/documentation.yml

**Comment by brenoepics** [comment]
@lewmilburn maybe you can add `maven-javadoc-plugin` to your `pom.xml` like
```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.10.0</version>
        <configuration>
        </configuration>
</plugin>
```

and something like `mvn javadoc:javadoc` might generate `target/report/apidocs`

**Comment by poyrazinan** [comment]
> Hello,
> 
> I encountered the same issue and was able to resolve it by adding the following option to the .yml file after `target-folder`:
> 
> ```yaml
> javadoc-source-folder: target/report/apidocs
> ```
> 
> This change points to the correct folder where the Javadoc is generated. Once I updated this in the workflow, the deployment worked as expected.
> 
> I hope this helps!

Thank you that fixed my issue.

Added this: `javadoc-source-folder: target/reports/apidocs`
